### ISSUE TITLE
First try, error with -l

### ISSUE THREAD

**Issue by idchlife** [brandon-rhodes/uncommitted#25]
```python
uncommitted -l /Users/igorandreev/www 
Traceback (most recent call last):
  File "/usr/local/bin/uncommitted", line 11, in <module>
    load_entry_point('uncommitted==1.9', 'console_scripts', 'uncommitted')()
  File "/usr/local/lib/python3.6/site-packages/uncommitted/command.py", line 217, in main
    repos.update(find_repos(path))
  File "/usr/local/lib/python3.6/site-packages/uncommitted/command.py", line 49, in find_repositories_with_locate
    paths = check_output(command).strip('\0').split('\0')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by brandon-rhodes** [comment]
Thanks for letting me know! I rewrite all the internals to use bytes, which hopefully will keep this from happening again.

**Comment by idchlife** [comment]
@brandon-rhodes thanks for this wonderful tool!
