### ISSUE TITLE
Error while executing uncommitted

### ISSUE THREAD

**Issue by wighawag** [brandon-rhodes/uncommitted#37]
I am getting this error

I could not figure more info, even with verbose

```
Traceback (most recent call last):
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 38, in run
    return check_output(command, **kw).splitlines()
  File "d:\installations\x64\python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "d:\installations\x64\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "d:\installations\x64\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "d:\installations\x64\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Installations\x64\Python37\Scripts\uncommitted-script.py", line 11, in <module>
    load_entry_point('uncommitted==2.3', 'console_scripts', 'uncommitted')()
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 264, in main
    scan(repos, options)
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 188, in scan
    lines, subrepos = get_status(directory, ignore_set, options)
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 152, in status_subversion
    for line in run(['svn', 'st', '-v'], cwd=path):
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 43, in run
    .format(command[0], kw['cwd'].decode("UTF-8")))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by brandon-rhodes** [comment]
Interesting! It looks like a patch 195c868b00d7d5a30e49de2fd17bf4155f0ad39d contributed 2½ years ago both broke the ability to print that error message with `.format()` when running on Windows, and also entirely broke "uncommitted" when a sub-command (like git or svn) files to run under Python 2 (because `FileNotFoundError` is in that case not defined).

I have gone through and rewritten the code paths involved. Could you try installing directly from GitHub to see if my fix works?
```
pip install https://github.com/brandon-rhodes/uncommitted/archive/master.zip
```

**Comment by wighawag** [comment]
getting this now:

```
Traceback (most recent call last):
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 38, in run
    return check_output(command, cwd=fixed_cwd).splitlines()
  File "d:\installations\x64\python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "d:\installations\x64\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "d:\installations\x64\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "d:\installations\x64\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 187, in scan
    lines, subrepos = get_status(directory, ignore_set, options)
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 150, in status_subversion
    for line in run(['svn', 'st', '-v'], cwd=path):
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 42, in run
    raise ErrorCommandMissing(cwd, command[0])
uncommitted.command.ErrorCommandMissing: (b'D:\\BACKUPS\\quantum-stage\\svn\\quantumlibrary', 'svn')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Installations\x64\Python37\Scripts\uncommitted-script.py", line 11, in <module>
    load_entry_point('uncommitted==2.3', 'console_scripts', 'uncommitted')()
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 266, in main
    scan(repos, options)
  File "d:\installations\x64\python37\lib\site-packages\uncommitted\command.py", line 189, in scan
    output(b'{} - skipping: {!r} command not found\n'.format(*e.args))
AttributeError: 'bytes' object has no attribute 'format'
```

**Comment by wighawag** [comment]
oh the error come from one svn repo 
So I guess I just need to install svn

**Comment by brandon-rhodes** [comment]
Instead of having you leave `svn` uninstalled to test over and over again, I decided (as you'll see from the above commit) to add a real integration test for this case. It helped me get the code working again under both Python 2 and Python 3. I'll plan a release for next week to get this out officially. Thanks for letting me know about the failure!

**Comment by wighawag** [comment]
Nice work!
Thanks for this tool. really useful to not lose work :)

**Comment by brandon-rhodes** [comment]
Thanks, I'm glad it's been helpful!
